### ISSUE TITLE
Make data uploader

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/mirtarbase#3]

**Comment by Cojabi** [comment]
In the data from miRTarBase are missing values (NaN) in the target entrez ID column.
Row indeces with missing values:
[  870  4555  4557  4558  4559  4560  4561  5251  5253  5254  5255  5256
  5257  5376  5454  5548  6302  7039  7351  7352  7367  7369  7921  8012
 23485]

@cthoyt How shall we handle those? Just exclude them or allow Entrez ID (which we defined as unique) to be null?
The corresponding Entrez IDs to the genes are listed at HGNC though. Don't know why they did not include those.

**Comment by cthoyt** [comment]
Hmm it's possible that entrez has not yet assigned gene ids for those Mirnas. I assume they do all have Mirna names though. If that's the case, then make entrez Id billable and we'll do some post processing later to see if we can match their names with mirbase entries

**Comment by cthoyt** [comment]
Oh, I misread. Alternate idea: email the mirTarBase people explaining the issue and if you could provide them a fix, is sure they'll be happy. Let's keep the unique=true for this column and throw out those entries for now
